// Mirrors lib/resources.js on the server. Kept as a plain browser script
// (no bundler/build step in this project) — if you add a new field on the
// server, add the matching entry here too.
window.CMS_COLLECTIONS = {
  'social-links': {
    label: 'Social Links', icon: 'fas fa-share-nodes',
    titleField: 'platform', imageField: null, publishField: 'visible', featuredField: null,
    fields: [
      { name: 'platform', label: 'Platform', type: 'text', required: true },
      { name: 'url', label: 'URL', type: 'url', required: true },
      { name: 'icon', label: 'Icon (Font Awesome class)', type: 'text', placeholder: 'fab fa-github' },
      { name: 'label', label: 'Label', type: 'text' },
    ],
  },
  skills: {
    label: 'Skills', icon: 'fas fa-gauge-high',
    titleField: 'name', imageField: null, publishField: 'visible', featuredField: 'featured',
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'category', label: 'Category', type: 'text', required: true, placeholder: 'Programming Languages' },
      { name: 'icon', label: 'Icon (Font Awesome class)', type: 'text', placeholder: 'fas fa-code' },
      { name: 'level', label: 'Level (0-100)', type: 'number', min: 0, max: 100 },
    ],
  },
  projects: {
    label: 'Projects', icon: 'fas fa-diagram-project',
    titleField: 'title', imageField: 'image', publishField: 'published', featuredField: 'featured',
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'shortDesc', label: 'Short Description', type: 'textarea' },
      { name: 'fullDesc', label: 'Full Description', type: 'richtext' },
      { name: 'image', label: 'Cover Image', type: 'image' },
      { name: 'images', label: 'Gallery Images (URLs)', type: 'json-list' },
      { name: 'technologies', label: 'Technologies', type: 'json-tags' },
      { name: 'category', label: 'Category', type: 'text' },
      { name: 'githubUrl', label: 'GitHub URL', type: 'url' },
      { name: 'liveUrl', label: 'Live / Demo URL', type: 'url' },
      { name: 'date', label: 'Date', type: 'text', placeholder: 'e.g. 2025' },
      { name: 'client', label: 'Client / Company', type: 'text' },
      { name: 'role', label: 'Role', type: 'text' },
      { name: 'features', label: 'Key Features', type: 'json-tags' },
    ],
  },
  certificates: {
    label: 'Certificates', icon: 'fas fa-award',
    titleField: 'name', imageField: 'image', publishField: 'published', featuredField: 'featured',
    fields: [
      { name: 'name', label: 'Certificate Name', type: 'text', required: true },
      { name: 'organization', label: 'Issuing Organization', type: 'text', required: true },
      { name: 'issueDate', label: 'Issue Date', type: 'text', placeholder: 'June 2025' },
      { name: 'expiryDate', label: 'Expiry Date', type: 'text' },
      { name: 'credentialId', label: 'Credential ID', type: 'text' },
      { name: 'credentialUrl', label: 'Credential URL', type: 'url' },
      { name: 'image', label: 'Certificate Image', type: 'image' },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'skills', label: 'Related Skills', type: 'json-tags' },
    ],
  },
  experience: {
    label: 'Experience', icon: 'fas fa-briefcase',
    titleField: 'position', imageField: 'logo', publishField: 'visible', featuredField: null,
    fields: [
      { name: 'position', label: 'Position / Title', type: 'text', required: true },
      { name: 'company', label: 'Company', type: 'text', required: true },
      { name: 'startDate', label: 'Start Date', type: 'text' },
      { name: 'endDate', label: 'End Date', type: 'text' },
      { name: 'current', label: 'Current Position', type: 'boolean' },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'responsibilities', label: 'Responsibilities', type: 'json-tags' },
      { name: 'technologies', label: 'Technologies', type: 'json-tags' },
      { name: 'logo', label: 'Company Logo', type: 'image' },
      { name: 'location', label: 'Location', type: 'text' },
    ],
  },
  education: {
    label: 'Education', icon: 'fas fa-graduation-cap',
    titleField: 'degree', imageField: 'logo', publishField: 'visible', featuredField: null,
    fields: [
      { name: 'degree', label: 'Degree', type: 'text', required: true },
      { name: 'institution', label: 'Institution', type: 'text', required: true },
      { name: 'program', label: 'Program', type: 'text' },
      { name: 'startDate', label: 'Start Date', type: 'text' },
      { name: 'endDate', label: 'End Date', type: 'text' },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'grade', label: 'Grade / CGPA', type: 'text' },
      { name: 'logo', label: 'Institution Logo', type: 'image' },
      { name: 'location', label: 'Location', type: 'text' },
    ],
  },
  services: {
    label: 'Services', icon: 'fas fa-concierge-bell',
    titleField: 'name', imageField: 'image', publishField: 'visible', featuredField: null,
    fields: [
      { name: 'name', label: 'Service Name', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'icon', label: 'Icon (Font Awesome class)', type: 'text' },
      { name: 'image', label: 'Image', type: 'image' },
      { name: 'technologies', label: 'Technologies', type: 'json-tags' },
      { name: 'features', label: 'Features', type: 'json-tags' },
      { name: 'priceLabel', label: 'Price Label', type: 'text', placeholder: 'from $20' },
    ],
  },
  achievements: {
    label: 'Achievements', icon: 'fas fa-trophy',
    titleField: 'title', imageField: 'image', publishField: 'visible', featuredField: 'featured',
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'date', label: 'Date', type: 'text' },
      { name: 'image', label: 'Image', type: 'image' },
      { name: 'organization', label: 'Organization', type: 'text' },
      { name: 'url', label: 'URL', type: 'url' },
      { name: 'number', label: 'Number (stat)', type: 'number' },
      { name: 'suffix', label: 'Suffix', type: 'text', placeholder: '+' },
      { name: 'icon', label: 'Icon (Font Awesome class)', type: 'text' },
    ],
  },
  testimonials: {
    label: 'Testimonials', icon: 'fas fa-quote-right',
    titleField: 'name', imageField: 'image', publishField: 'published', featuredField: null,
    fields: [
      { name: 'name', label: 'Person Name', type: 'text', required: true },
      { name: 'role', label: 'Role', type: 'text' },
      { name: 'company', label: 'Company', type: 'text' },
      { name: 'image', label: 'Photo', type: 'image' },
      { name: 'text', label: 'Testimonial', type: 'textarea', required: true },
      { name: 'rating', label: 'Rating (1-5)', type: 'number', min: 1, max: 5 },
      { name: 'url', label: 'LinkedIn / Website URL', type: 'url' },
    ],
  },
};

window.CMS_SINGLETONS = {
  profile: {
    label: 'Profile', icon: 'fas fa-id-badge',
    fields: [
      { name: 'fullName', label: 'Full Name', type: 'text', required: true },
      { name: 'displayName', label: 'Display Name / Short Name', type: 'text' },
      { name: 'title', label: 'Professional Title', type: 'text' },
      { name: 'introShort', label: 'Short Introduction', type: 'textarea' },
      { name: 'email', label: 'Email', type: 'email' },
      { name: 'phone', label: 'Phone', type: 'text' },
      { name: 'whatsapp', label: 'WhatsApp Number', type: 'text' },
      { name: 'location', label: 'Location', type: 'text' },
      { name: 'availability', label: 'Availability', type: 'text', placeholder: 'Open to Work' },
      { name: 'profileImage', label: 'Profile Image', type: 'image' },
      { name: 'resumeUrl', label: 'Resume / CV File', type: 'image' },
    ],
  },
  hero: {
    label: 'Hero Section', icon: 'fas fa-house',
    fields: [
      { name: 'heading', label: 'Main Heading', type: 'text' },
      { name: 'name', label: 'Name (as displayed)', type: 'text' },
      { name: 'typedRoles', label: 'Typed Roles (rotating text)', type: 'json-tags' },
      { name: 'subtitle', label: 'Subtitle', type: 'text' },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'ctaText', label: 'Primary Button Text', type: 'text' },
      { name: 'ctaUrl', label: 'Primary Button URL', type: 'text' },
      { name: 'ctaSecondaryText', label: 'Secondary Button Text', type: 'text' },
      { name: 'ctaSecondaryUrl', label: 'Secondary Button URL', type: 'text' },
      { name: 'heroImage', label: 'Hero Image', type: 'image' },
      { name: 'statusText', label: 'Availability / Status Text', type: 'text' },
    ],
  },
  about: {
    label: 'About Section', icon: 'fas fa-user',
    fields: [
      { name: 'greeting', label: 'Greeting label', type: 'text', placeholder: 'Who I Am' },
      { name: 'heading', label: 'Heading', type: 'text' },
      { name: 'subheading', label: 'Subheading', type: 'text' },
      { name: 'paragraphs', label: 'Paragraphs', type: 'json-list' },
      { name: 'tags', label: 'Highlight Tags', type: 'json-tags-obj' },
      { name: 'image', label: 'Image', type: 'image' },
    ],
  },
  contact: {
    label: 'Contact Information', icon: 'fas fa-envelope',
    fields: [
      { name: 'email', label: 'Email', type: 'email' },
      { name: 'phone', label: 'Phone', type: 'text' },
      { name: 'whatsapp', label: 'WhatsApp Number', type: 'text' },
      { name: 'location', label: 'Location', type: 'text' },
      { name: 'availability', label: 'Availability', type: 'text' },
    ],
  },
  seo: {
    label: 'SEO', icon: 'fas fa-magnifying-glass-chart',
    fields: [
      { name: 'siteTitle', label: 'Website Title', type: 'text' },
      { name: 'metaDescription', label: 'Meta Description', type: 'textarea' },
      { name: 'keywords', label: 'Keywords (comma separated)', type: 'text' },
      { name: 'author', label: 'Author', type: 'text' },
      { name: 'ogTitle', label: 'Open Graph Title', type: 'text' },
      { name: 'ogDescription', label: 'Open Graph Description', type: 'textarea' },
      { name: 'ogImage', label: 'Open Graph Image', type: 'image' },
      { name: 'twitterHandle', label: 'Twitter / X Handle', type: 'text' },
      { name: 'canonicalUrl', label: 'Canonical URL', type: 'url' },
    ],
  },
  'site-settings': {
    label: 'Site Settings', icon: 'fas fa-sliders',
    fields: [
      { name: 'maintenanceMode', label: 'Maintenance Mode', type: 'boolean' },
      { name: 'footerText', label: 'Footer Text', type: 'text' },
      { name: 'gaId', label: 'Google Analytics ID', type: 'text' },
      { name: 'themeColor', label: 'Theme Color', type: 'text' },
    ],
  },
};
